### ISSUE TITLE
Patterns workshop notes (26/10)

### ISSUE THREAD

**Issue by yaili** [ubuntudesign/vanilla-dashboard-theme-design#1]
Attendees: @kwm14 @MariaVrachni @richmccartney @yaili
## Patterns to be included in dashboard theme from MAAS GUI theme:

Colour:
- Strip colour from theme, leave it at site/application level
- Use Vanilla theme

Tooltips:
- Design needs to be considered (too fat rounded corners?)

Accordion:
- Can we have as many panels open as we want?
- How do we deal with long tag lists?

Navigation:
- What's the highlighted colour?
- Include account links
- Include notification signal

Button group:
- Agree on pattern name

Buttons:
- Adopt Vanilla + Juju styles

Notifications:
- From Vanilla
- Does Landscape have local errors?
- How will the MAAS flash messages be treated? As notifications or different pattern?

List tree:
- Same design
- Make sure it’s ok to have links
- Does it need to be interactive? (e.g. checkboxes for each item)

Table columns and rows:
- Add a proposal to include this in Vanilla
- Review using percentages
- Review background colours for accessibility

Tabs:
- Scaling design (for many tab headers)
- Review highlight colour
- How does it work in mobile/responsive?

Interactive table:
- Include in dashboard but we still need to review internal components
- Responsive in progress
- Review possible actions inside tables in Landscape

Inline edit:
- Revisit for dashboard theme (accessibility and touch screens)

Search (global):
- Simple and useful to have

Forms:
1. Inline
2. Stacked
3. Default (already part of Vanilla)
- Revisit validation
  - Error message
  - Icons in field?
  - Border colour/style  
- Style of checkboxes and radio buttons
- Remove switcher
- Placeholder text
  - Should it include optional/required indication? Probably not
- Field description (include but needs to be reviewed)

Icons:
- Adopt Juju library style
- Icons need to be standardised across different apps

Typography:
- Use Vanilla theme

Code block:
- Needs to be redesigned for Vanilla (light background with syntax highlighting)

Utility classes:
- Include padding and margin classes
- Include loading spinner animation

Links:
- Awaiting results from Juju testing before adopting pattern

Tables:
- Currently no pagination designed (‘load more’ pattern)
- Examine sorting for columns (functionality and style)

## Other things we need to consider for dashboard theme:
- Should we add modals?
- Graphs (Spencer currently working on graphs for Juju)
- Table pagination
- Table filtering
- Dropdown (eg. Landscape account switcher) + dropdown full width (eg. Juju search midpoint style)
- Contextual menu (eg. Juju kebab icon in machine view)
- Notification signal
- Progress bar?
- Footer design
- Side bar menu (eg. Snapweb)

**Comment by yaili** [comment]
@richmccartney can you create the "Table columns and rows" proposal mentioned above in Vanilla?

**Comment by yaili** [comment]
Does anyone remember what notification signal is?

**Comment by kwm14** [comment]
@yaili Yes it was a recent feature for MAAS. It has been signed off but no implemented as of yet...

**Comment by yaili** [comment]
Is it the number of alerts in the main nav?

**Comment by kwm14** [comment]
@yaili yes the signal is shown in the main navigation top right and when you click, it will take you a notification centre depending what is used in our Cloud apps:

### Notification signal
![nav_notification_icon_v17](https://cloud.githubusercontent.com/assets/17748020/22016289/a94b5242-dc9d-11e6-85a0-8045de873e4c.png)

**Comment by yaili** [comment]
Closing this, think everything is captured in separate issues.
