### ISSUE TITLE
Finalise interactive table pattern design

### ISSUE THREAD

**Issue by yaili** [ubuntudesign/vanilla-dashboard-theme-design#12]
- Do not add review internal components for now
- Spec responsive behaviour

**Comment by yaili** [comment]
@kwm14 is there a MAAS tables design you can share here?

**Comment by kwm14** [comment]
@richmccartney has put together some demo pages on the MAAS GUI which may help, we've also just landed MAAS tables on mobile so I can provide some screenshots of those too.

**Demo listing page**
http://ubuntudesign.github.io/maas-gui-vanilla-theme/demo-listing.html

**Demo details page**
http://ubuntudesign.github.io/maas-gui-vanilla-theme/demo-details.html

**Comment by richmccartney** [comment]
All MAAS styles and elements are shown in these two demos.

**Comment by kwm14** [comment]
Design spec: https://github.com/ubuntudesign/vanilla-dashboard-theme-design/tree/master/Table%20responsive
