### ISSUE TITLE
Design spec for table sorting

### ISSUE THREAD

**Issue by yaili** [ubuntudesign/vanilla-dashboard-theme-design#15]
- When first arrive at table, nothing is selected, headings all look the same
- When user clicks on a heading, ascending arrow appears next to heading
- When user clicks on same heading again, descending arrow replaces ascending arrow

**Comment by matthewpaulthomas** [comment]
> When first arrive at table, nothing is selected, headings all look the same

This might be a little more visually elegant. But if a sortable table instead _always_ showed which column it was currently sorted by, it would be more obvious that it was sortable at all. And in some cases, not showing the current sort order may cause confusion about why a particular item isn’t visible. (Is it actually missing, or is it just scrolled out of view in a list that’s sorted some way I don’t immediately recognise?)

> When user clicks on a heading, ascending…

Many columns are much more useful sorted descending than ascending. Therefore, clicking the heading the first time sorts it descending, and you have to click a second time to get ascending. Current and future examples:
- files sorted by date in a file manager, or in Google Drive
- “% CPU” of processes in Landscape
- apps sorted by size on a device
- your published snaps sorted by number of installs, or by revenue.

> arrow appears next to heading

It is very common to use an arrow, or an isosceles triangle, in a column header to show sort order. But personally, I’m never sure which arrow/triangle represents which order; I have to click it a couple of times to check. I find it easier to understand icons that suggest actual items in order: ![column sorting icon 1](https://user-images.githubusercontent.com/19801137/28317655-be6bb5c0-6bbf-11e7-9af2-92900ffd3d0f.png) ![column sorting icon 2](https://user-images.githubusercontent.com/19801137/28317654-be67b07e-6bbf-11e7-8fac-fe8e5fad3bb0.png)

**Comment by yaili** [comment]
Spec: https://github.com/ubuntudesign/vanilla-dashboard-theme-design/tree/master/Table%20sorting

**Comment by anthonydillon** [comment]
Spec looks good. Thanks.
