### ISSUE TITLE
Should we include progress bar pattern?

### ISSUE THREAD

**Issue by yaili** [ubuntudesign/vanilla-dashboard-theme-design#18]

**Comment by anthonydillon** [comment]
Do we have progress bars in MAAS or landscape?

**Comment by yaili** [comment]
I think there were, but @kwm14 and @MariaVrachni will know more.

**Comment by kwm14** [comment]
@yaili @anthonydillon as far as I'm aware we don't have any progress bars in MAAS, but in Landscape when building your Cloud there is a progress bar at the final stage so show installation which looks like this:

![installing region 1 table progress](https://cloud.githubusercontent.com/assets/17748020/22016156/17ae861a-dc9d-11e6-943b-68d51a0c31f9.png)

**Comment by yaili** [comment]
Closing this issue for now. The only instance of a progress bar we can find is the one mentioned above in Landscape.
