### ISSUE TITLE
Switch design proposal

### ISSUE THREAD

**Issue by yaili** [ubuntudesign/vanilla-dashboard-theme-design#26]
Right now MAAS and Juju have switches that look different.

The proposal should have:
- No padding
- Try icons (like Juju) and words (On/Off)
- Colours (component blue for positive)

**Comment by kwm14** [comment]
### MAAS 

- Current switch used to enable/disable device discovery
![maas-example](https://user-images.githubusercontent.com/17748020/28307079-8ea1438a-6b99-11e7-9bbb-0e026cbf5ab6.png)

### Juju 

- Current switch used to expose your application
![juju-example](https://user-images.githubusercontent.com/17748020/28307151-cd09d498-6b99-11e7-93b6-a24ea2e0c1f3.png)

**Comment by kwm14** [comment]
### Suru 

- Concepts of switches created by Jamie for platform
![suru-switch-concepts](https://user-images.githubusercontent.com/17748020/28312255-672b4e3e-6baa-11e7-9b57-df85bccd2629.png)

**Comment by matthewpaulthomas** [comment]
Here are [the design guidelines I wrote](https://docs.google.com/document/d/1Ami5HfKQFmFqmJGSdYQmCidv1T4NPM3ecJL3y3PvyWs/edit#heading=h.z9ya44kd3b9k) (Canonical-only link) for those switches that Jamie mocked up above:
> **Use** a switch for a mode or something that is most easily understood as being on or off: for example, “Do Not Disturb”, “Flight Mode”, or “Call waiting”. Otherwise use:
> - a **checkbox**, for an option that is most easily understood as an instruction from the user to the system (for example, “Show password” or “Notify me when a contact comes online”), or a property that is or isn’t applied to something (for example, “Bold” or “Italic”); or
> - a pair of **radio buttons**, if there is space to show labels for both values at once; or
> - a **radio menu**.
>
> **Label** a switch using a proper noun or noun phrase representing the mode: for example, “Automatic backups”.

If it was following these guidelines, Maas’s “Discovery enabled” above should be shortened to “Discovery”. (Every switch is for enabling something!) And Juju’s “Expose application” should be a checkbox rather than a switch, since it’s an instruction from the user to the system.

**Comment by kwm14** [comment]
## New design proposal

- Influence from Jamie's concepts
- No padding
- Include words 'On/Off' for accessibility (MAAS)
- Colours (component blue for positive)
- Icon sizes: 64px and 32px

![new-switch-proposal](https://user-images.githubusercontent.com/17748020/28373203-a7db425a-6c99-11e7-9662-a8c0a548f84e.png)

**Comment by kwm14** [comment]
## Proposal applied to MAAS

- updated label based on Matthew's feedback
- updated to new information icon
- showing both actions on/off

![maas-example-switch-off](https://user-images.githubusercontent.com/17748020/28409675-325e0ca2-6d33-11e7-947d-a71f53f61e0f.png)

![maas-example-switch-on](https://user-images.githubusercontent.com/17748020/28409681-373d6ff6-6d33-11e7-9099-238fe55cba38.png)

**Comment by anthonydillon** [comment]
All agreed with the design. Only need the 32px version. Will need to review the use of On/Off in all cases.

**Comment by kwm14** [comment]
Design spec: https://github.com/ubuntudesign/vanilla-dashboard-theme-design/tree/master/Switch
