### ISSUE TITLE
Vanilla working group notes (31/10)

### ISSUE THREAD

**Issue by kwm14** [ubuntudesign/vanilla-dashboard-theme-design#3]
Me and @MariaVrachni talked to the Vanilla team about our Dashboard theme kick-off. We discussed what happened in our day workshop, went through our notes and our actions going forward.

A few comments were discussed in the meeting:

- Take into account when reviewing and proposing patterns that Vanilla comes first
- Could some patterns proposed for Dashboard theme go into Vanilla as a base?
- Status on Rich's progress of converting MAAS GUI to Dashboard theme
- Rich to create a separate pull request when building components
- Vanilla team to QA code in Dashboard theme

**Comment by yaili** [comment]
Closing as there is no action. Re-open if needed. :)
