### ISSUE TITLE
[Contextual menu] Improve the behaviour so that the menu is introduced only if there is a greater number of actions that [x]

### ISSUE THREAD

**Issue by MariaVrachni** [ubuntudesign/vanilla-dashboard-theme-design#30]
## Description

Currently in the MAAS UI we have all the row actions in contextual menus, even if only one action is available, which hides the action and introduces more clicks to perform it. 

I propose we introduce a specification for the contextual menu that defines the minimum number of actions that need to be available in order to introduce the menu.

**Comment by kwm14** [comment]
Issue moved to [ubuntudesign/vanilla-design #104](https://github.com/ubuntudesign/vanilla-design/issues/104) via [**ZenHub**](https://www.zenhub.com/)
