### ISSUE TITLE
Finalise navigation pattern design

### ISSUE THREAD

**Issue by kwm14** [ubuntudesign/vanilla-dashboard-theme-design#4]
In our kick-off meeting we discussed which navigation should go into the Dashboard theme.

**Questions raised**
- What's the highlighted colour?
- Include account links?
- Include notification signal? (MAAS proposal)

I thought it would be good to see which navigation patterns we currently use across our products and decide which best fits, or whether we need to update Vanilla to be the base layer.

### Vanilla 1.0
![navigation_vanilla](https://cloud.githubusercontent.com/assets/17748020/19935604/8ef40a86-a112-11e6-85a2-f950e20f8aff.jpg)

### Landscape - not mobile responsive
![navigation_landscape](https://cloud.githubusercontent.com/assets/17748020/19936362/13906fda-a115-11e6-8577-0973bf7e58be.jpg)

### MAAS
![navigation_maas](https://cloud.githubusercontent.com/assets/17748020/19935624/a2ccc110-a112-11e6-91ab-e4e6e02b669a.jpg)

### Snapweb
![navigation_snapweb](https://cloud.githubusercontent.com/assets/17748020/19935616/9aaddd8e-a112-11e6-92a2-fb9f30a09c99.jpg)

### Juju
![navigation_juju](https://cloud.githubusercontent.com/assets/17748020/19935638/ac256ed8-a112-11e6-9420-90fa91bef9e1.jpg)

**Comment by yaili** [comment]
This is related to https://github.com/ubuntudesign/vanilla-design/issues/27

**Comment by kwm14** [comment]
Issue moved to [ubuntudesign/vanilla-design #103](https://github.com/ubuntudesign/vanilla-design/issues/103) via [**ZenHub**](https://www.zenhub.com/)
