### ISSUE TITLE
Code block pattern design (to be implemented in Vanilla)

### ISSUE THREAD

**Issue by kwm14** [ubuntudesign/vanilla-dashboard-theme-design#5]
In our kick-off meeting we discussed which code block should go into the Dashboard theme, or whether it just needs to be redesigned for Vanilla with a light background with syntax highlighting version.

Currently across our products we use black and white code blocks which share the same pattern across MAAS, Juju and Vanilla. But the only difference is border style:

### MAAS - border-radius: 8px
![code_block_maas](https://cloud.githubusercontent.com/assets/17748020/19965642/eac097b4-a1bf-11e6-92ea-c35b59bbee86.jpg)

### Juju/Vanilla - border-radius: 2px
![vanilla](https://cloud.githubusercontent.com/assets/17748020/19965649/f62297ec-a1bf-11e6-89f9-ea4224438ac7.jpg)

In regards to redesigning a light background with syntax highlighting, we have actually implemented this on snapcraft.io but also has a different border style:

### snapcraft.io - border-radius: 4px
![code_block_snapcraft io](https://cloud.githubusercontent.com/assets/17748020/19965677/1837c190-a1c0-11e6-9ffd-fc90f68d0831.jpg)

**Comment by yaili** [comment]
Vanillla issue: https://github.com/ubuntudesign/vanilla-framework/issues/818

**Comment by barrymcgee** [comment]
Addressed by #835
