### ISSUE TITLE
Finalise tooltip design

### ISSUE THREAD

**Issue by yaili** [ubuntudesign/vanilla-dashboard-theme-design#7]
Are the current rounded corners too fat?

**Comment by kwm14** [comment]
@yaili MAAS and Juju use the same radius of 2px so I don't think the corners are too fat.

**Comment by yaili** [comment]
Mmm, I think we saw some example where they were fatter. @spencerbygraves anything on Juju maybe?

**Comment by spencerbygraves** [comment]
@yaili we've been using 2px as a corner radius for a while, so there shouldn't be.

**Comment by yaili** [comment]
OK. Sounds good to me then.
