### ISSUE TITLE
Improvements to accordion pattern

### ISSUE THREAD

**Issue by yaili** [ubuntudesign/vanilla-dashboard-theme-design#8]
- Can we have as many panels open as we want?
- How do we deal with long tag lists?

**Comment by kwm14** [comment]
@yaili currently in MAAS we can only have one panel open at any time, and regarding long tags there is a height limit before the panel content becomes scrollable. @richmccartney will be able to clarify the exact height.

**Comment by yaili** [comment]
@kwm14 Cool. We said we needed to look into these two issues to add the pattern to the dashboard theme. I'm trying to separate the initial workshop notes into more clear issues to be worked on :)

**Comment by yaili** [comment]
Spec: https://github.com/ubuntudesign/vanilla-dashboard-theme-design/tree/master/Accordion
